Header header
#vehicle info to remote
float32 Vehicle_speed #run time speed km/h
float32 Vehicle_steer #run time angle °
float32 Vehicle_angular_velocity # run time angular velocity(behind wheel) rad/s
float32 wheel_speed_FL #run time front left speed km/h
float32 wheel_speed_FR #run time front right speed km/h
float32 wheel_speed_BL #run time behind left speed km/h
float32 wheel_speed_BR #run time behind left speed km/h
int8    CURRENT_GEAR 
float32 steering_angle_speed
float32 ESP_MasterCylindBrakePress
float32 ESP_WheelCylindBrakePress
int8    AccPedalPos
int8    BrakePedalStatus
float32 engine_RPM
float32 NetEngTrq
float32 VehDynYawRate
float32 LateralAcce
