Header header

string IP
uint8 Machine_type
string Machine_ID
float32 Machine_len
float32 Machine_width
float32 Machine_height
float32 Machine_working_radius
float32 Machine_self_weight

float32 Carrying_weight

accuracy_gps Gps_precision
float64 Gps_Latitude
float64 Gps_Longitude
float64 Gps_Height
float32 Heading
float32 Velocity
float32 Acceleration
float32 turn_rate

float32 Arm_angle1_swing #swing
float32 Arm_angle2_boom #boom
float32 Arm_angle3_stick #stick
float32 Arm_angle4_bucket #bucket

float64 Bucket_latitude
float64 Bucket_longitude
float64 Bucket_altitude
